# Generated by Django 5.2.5 on 2025-11-14 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='EN_PROCESO', max_length=20)),
                ('total_registros', models.IntegerField(blank=True, null=True)),
                ('procesados_ok', models.IntegerField(blank=True, null=True)),
                ('procesados_err', models.IntegerField(blank=True, null=True)),
                ('errores', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'archivo_carga',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('formato', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('ZIP', 'ZIP')], max_length=4, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONA_NATURAL', 'Persona natural'), ('PERSONA_JURIDICA', 'Persona jurídica')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_legal', models.CharField(max_length=200)),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=180, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=240, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Partys',
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('correo', models.EmailField(max_length=180, unique=True)),
                ('hash_password', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada'), ('PENDIENTE_APROBACION', 'Pendiente aprobación'), ('RECHAZADA', 'Rechazada')], default='VIGENTE', max_length=24)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('CARGA_MASIVA', 'Carga masiva'), ('API', 'API')], default='MANUAL', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archivo_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='appNuam.archivocarga')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='appNuam.party')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to='appNuam.usuario')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_eliminadas', to='appNuam.usuario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_actualizadas', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='appNuam.documento'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('emitido_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partys_creados', to='appNuam.usuario'),
        ),
        migrations.AddField(
            model_name='party',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partys_eliminados', to='appNuam.usuario'),
        ),
        migrations.AddField(
            model_name='party',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partys_actualizados', to='appNuam.usuario'),
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('ANULAR', 'Anular'), ('RESTAURAR', 'Restaurar')], max_length=15)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='appNuam.calificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'historial_accion',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to='appNuam.usuario'),
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_creadas', to='appNuam.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_usuarios', to='appNuam.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_roles', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'usuario_roles',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='appNuam.UsuarioRol', to='appNuam.rol'),
        ),
        migrations.CreateModel(
            name='ArchivoCargaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_numero', models.IntegerField()),
                ('datos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OK', 'Correcto'), ('ERROR', 'Error'), ('ADVERTENCIA', 'Advertencia')], default='ERROR', max_length=20)),
                ('errores', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appNuam.archivocarga')),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_carga', to='appNuam.calificacion')),
            ],
            options={
                'db_table': 'archivo_carga_detalle',
                'indexes': [models.Index(fields=['archivo_carga', 'fila_numero'], name='idx_carga_det_fila'), models.Index(fields=['estado'], name='idx_carga_det_estado')],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO_TRIBUTARIO', 'Certificado tributario'), ('REPORTE_AUDITORIA', 'Reporte auditoría'), ('EXPORTACION', 'Exportación'), ('BACKUP', 'Backup')], max_length=40)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('ZIP', 'ZIP')], default='PDF', max_length=4)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='appNuam.calificacion')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='appNuam.documento')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='appNuam.party')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'reportes',
                'indexes': [models.Index(fields=['tipo', 'created_at'], name='idx_reportes_tipo_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['rut'], name='idx_party_rut'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tipo'], name='idx_party_tipo'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['party', 'fecha'], name='idx_calif_party_fecha'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='idx_calif_estado'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fuente'], name='idx_calif_fuente'),
        ),
        migrations.AddIndex(
            model_name='archivocarga',
            index=models.Index(fields=['estado'], name='idx_carga_estado'),
        ),
        migrations.AddIndex(
            model_name='archivocarga',
            index=models.Index(fields=['created_at'], name='idx_carga_created_at'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uniq_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='idx_usuarios_correo'),
        ),
    ]
