# Generated by Django 5.2.5 on 2025-12-11 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('id', models.AutoField(db_column='id_accionista', primary_key=True, serialize=False)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'accionistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.AutoField(db_column='id_carga', primary_key=True, serialize=False)),
                ('archivo_normalizado', models.IntegerField(blank=True, db_column='id_archivo_normalizado', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('total_filas', models.IntegerField(blank=True, null=True)),
                ('filas_ok', models.IntegerField(blank=True, null=True)),
                ('filas_error', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=32)),
                ('resumen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargas_masivas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoCargaDetalle',
            fields=[
                ('id', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('fila_numero', models.IntegerField(db_column='nro_fila')),
                ('estado', models.CharField(max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargas_masivas_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoFuente',
            fields=[
                ('id', models.AutoField(db_column='id_archivo_fuente', primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_archivo', models.TextField()),
                ('origen', models.CharField(default='usuario', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_proceso', models.CharField(default='pendiente', max_length=20)),
                ('extraido_por_ia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'archivos_fuente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.AutoField(db_column='id_calificacion', primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_registro', models.CharField(choices=[('vigente', 'Vigente'), ('reemplazado', 'Reemplazado'), ('anulado', 'Anulado')], default='vigente', max_length=12)),
                ('origen', models.CharField(default='manual', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado_proceso', models.CharField(choices=[('pendiente', 'Pendiente'), ('terminada', 'Terminada'), ('rechazada', 'Rechazada')], db_column='estado_proceso', default='pendiente', max_length=12)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificaciones_tributarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.AutoField(db_column='id_contador', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(db_column='id_documento', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('ruta_archivo', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('visibilidad', models.CharField(default='empleados', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.AutoField(db_column='id_emisor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_emisor', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emisores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmisorContador',
            fields=[
                ('id', models.AutoField(db_column='id_emisor_contador', primary_key=True, serialize=False)),
                ('rol_relacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emisores_contadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmisorUsuario',
            fields=[
                ('id', models.AutoField(db_column='id_emisor_usuario', primary_key=True, serialize=False)),
                ('rol_emisor', models.CharField(default='REPRESENTANTE', max_length=30)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emisor_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=15)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(db_column='id_instrumento', primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_instrumento', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'instrumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inversionista',
            fields=[
                ('id', models.AutoField(db_column='id_inversionista', primary_key=True, serialize=False)),
                ('tipo_inversionista', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inversionistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('formato', models.CharField(default='PDF', max_length=4)),
                ('party_id', models.IntegerField(blank=True, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jwt_id', models.CharField(max_length=255)),
                ('emitido_at', models.DateTimeField()),
                ('expira_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_desvinculacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(db_column='id_usuario_rol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_plain', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debug_info', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'usuarios_debug',
            },
        ),
    ]
