# Generated by Django 5.2.5 on 2025-11-28 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aprobaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='EN_PROCESO', max_length=20)),
                ('total_registros', models.IntegerField(blank=True, null=True)),
                ('procesados_ok', models.IntegerField(blank=True, null=True)),
                ('procesados_err', models.IntegerField(blank=True, null=True)),
                ('errores', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'archivo_carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoCargaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_numero', models.IntegerField()),
                ('datos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OK', 'Correcto'), ('ERROR', 'Error'), ('ADVERTENCIA', 'Advertencia')], default='ERROR', max_length=20)),
                ('errores', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'archivo_carga_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=120)),
                ('objeto', models.CharField(blank=True, max_length=120, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auditoria_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BackupEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='DESCONOCIDO', max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'backup_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada'), ('PENDIENTE_APROBACION', 'Pendiente aprobacion'), ('RECHAZADA', 'Rechazada')], default='VIGENTE', max_length=24)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('CARGA_MASIVA', 'Carga masiva'), ('API', 'API')], default='MANUAL', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('ANULAR', 'Anular'), ('RESTAURAR', 'Restaurar'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar')], max_length=15)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'historial_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('formato', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('ZIP', 'ZIP')], max_length=4, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('ANULAR', 'Anular'), ('RESTARURAR', 'Restaurar')], max_length=15)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'historial_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformeOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'informes_oficiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=500)),
                ('tipo', models.CharField(default='str', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'parametros_sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONA_NATURAL', 'Persona natural'), ('PERSONA_JURIDICA', 'Persona juridica')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_legal', models.CharField(max_length=200)),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=180, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=240, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Partys',
                'db_table': 'party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('expresion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reglas_negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO_TRIBUTARIO', 'Certificado tributario'), ('REPORTE_AUDITORIA', 'Reporte auditoria'), ('EXPORTACION', 'Exportacion'), ('BACKUP', 'Backup')], max_length=40)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('ZIP', 'ZIP')], default='PDF', max_length=4)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('emitido_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('desvinculado', 'Desvinculado')], default='activo', max_length=15)),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now)),
                ('ultimo_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, db_column='fecha_bloqueo', null=True)),
                ('fecha_desvinculacion', models.DateTimeField(blank=True, db_column='fecha_desvinculacion', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.AutoField(db_column='id_usuario_rol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
    ]
